export const b1= [
  "Normalization exponent for bond stress, uncracked concrete, diamond drilled holes"
,"Normalization exponent for bond stress, cracked concrete, diamond drilled holes"
,"Normalization exponent for bond stress, uncracked concrete, diamond drilled + roughening tool"
,"Normalization exponent for bond stress, cracked concrete, diamond drilled + roughening tool",
,"Anchor category, hammer drilled, dry concrete"
,"Strength reduction factor, bond tension, hammer drilled holes, dry concrete, cond. B"
,"Resistance modification factor, bond tension, hammer drilled holes, dry concrete, cond. B"
,"Anchor category, hammer drilled, water saturated concrete"
,"Strength reduction factor, bond tension, hammer drilled holes, water saturated concrete, cond. B"
,"Resistance modification factor, bond tension, hammer drilled holes, water saturated concrete, cond. B"
,"Anchor category, hammer drilled, water filled holes"
,"Strength reduction factor, bond tension, hammer drilled holes, water filled holes, cond. B"
,"Resistance modification factor, bond tension, hammer drilled holes, water filled holes, cond. B"
,"Anchor category, hammer drilled, under water"
,"Strength reduction factor, bond tension, hammer drilled holes, under water, cond. B"
,"Resistance modification factor, bond tension, hammer drilled holes, under water, cond. B"
,"Anchor category, diamond drilled, dry concrete"
,"Strength reduction factor, bond tension, diamond cored holes in dry concrete, cond. B"
,"Resistance modification factor, bond tension, diamond cored holes in dry concrete, cond. B"
,"Anchor category, diamond drilled, water saturated concrete"
,"Strength reduction factor, bond tension, diamond cored holes in water saturated concrete, cond. B"
,"Resistance modification factor, bond tension, diamond cored holes in water saturated concrete, cond. B"
,"Anchor category, diamond drilled, water filled holes"
,"Strength reduction factor, bond tension, diamond cored holes, water filled holes, cond. B"
,"Resistance modification factor, bond tension, diamond cored holes, water filled holes, cond. B"
,"Anchor category, diamond drilled, under water"
,"Strength reduction factor, bond tension, diamond cored holes, under water, cond. B"
,"Resistance modification factor, bond tension, diamond cored holes, under water, cond. B"
,"Anchor category, diamond drilled + roughening tool, dry concrete"
,"Strength reduction factor, bond tension, diamond cored + roughened holes, dry concrete, cond. B"
,"Resistance modification factor, bond tension, diamond cored + roughened holes, dry concrete, cond. B"
,"Anchor category, diamond drilled + roughening tool, water saturated concrete"
,"Strength reduction factor, bond tension, diamond cored + roughened holes in water saturated concrete, cond. B"
,"Resistance modification factor, bond tension, diamond cored + roughened holes in water saturated concrete, cond. B"
,"Anchor category, diamond drilled + roughening tool, water filled holes"
,"Strength reduction factor, bond tension, diamond cored + roughened holes, water filled holes, cond. B"
,"Resistance modification factor, bond tension, diamond cored + roughened holes, water filled holes, cond. B"
,"Anchor category, diamond drilled + roughening tool, under water"
,"Strength reduction factor, bond tension, diamond cored + roughened holes, under water, cond. B"
,"Resistance modification factor, bond tension, diamond cored + roughened holes, under water, cond. B"
,"Reduction for seismic tension"
,"Product can be used with ICC"
,"Product can be used with the HNA methods ACI 318-11 and ACI 318-14"
,"Product can be used with CSA"
,"Product can be used with the HNA method ACI 349-01"
,"Product is NOT allowed for seismic in ACI methods (mechanical anchors)"
,"Product is NOT allowed for seismic in CSA methods (mechanical anchors)"
,"Product is allowed for use in Concrete Over Metal Deck applications"
,"A “shear warning” should be shown in the report for the fastener (KH-EZ I)"
,"Anchor-family is allowed with stand-off fastening without clamping"
,"Anchor-family is allowed with stand-off fastening with clamping"
,"Anchor-family is allowed with stand-off fastening with grouting"
,"Anchor-family needs no installation torque moment (T_inst = 0) or cannot be tightened"
,"Anchor-family is approved for use in cracked concrete (tensile zone)"
,"Anchor-family should be shown if uncracked concrete is selected in the UI (filter criteria for “special” HRD anchors)"
,"Anchor-family is approved for use under dynamic loading (design methods DIBt-Dyn and Hilti-Dyn)"
,"Anchor-family is approved for use in shock conditions"
,"Anchor-family is approved for use under seismic loading (design methods Hilti-ASD and ACI 318 - AC193/AC308/CIP)"
,"Anchor-family is approved for use with the Dynamic Set"
,"Anchor-Family can be installed using the AT tool (special setting tool in USA + Canada)"
]